# Generated by Django 5.1.3 on 2024-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detect_popularity_prediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_id', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('post_desc', models.CharField(max_length=300)),
                ('score', models.CharField(max_length=300)),
                ('created_dt', models.CharField(max_length=300)),
                ('lat', models.CharField(max_length=300)),
                ('lon', models.CharField(max_length=300)),
                ('u_city', models.CharField(max_length=300)),
                ('u_country', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
